language: scala

scala:
  - 2.12.4
  - 2.11.12

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: Pi8lp600+lcN6Q/E5JsdP2eMgORLr3F7YebvX8G/Lk9gVb1PJKqGoWwx8FH7Ey2brlFP+EFUHcnRYhh1mKUp+1AgYfmhdBLgBJo1rW7zRuzJrrIgZc+iabi+NZiXIyHJs81glslmPV0/GnRaQzWUJPUFi6DierSbrFglk+Kk6Vhk7JJoxGw9xG39u4UuI3ahySDOunrF+eTCH6FrZceYQ17mdjBSfgshHC5jNFaEtlLwy5MqffjR5zTd7WBxSEUGD6QFmzFbch15UMUOYhwUslGyU6b5xWM6jt0/yUcQByaVO9yzc+mCuVd1mYuMCC1y+GjDg6LXc7wFIET31SEbMvZ5y2w89l8Y+Eo347h24r1sJog58EVdxBxGR+mBGaUFEdiyDGXUFPvSAv7fyfg2s1aGnkCOCTB26Ro8NBphAC3nl3kdRRI9kKZdvjUppFyURqod7o94C2F5t32ytKcJtUbHUT9PDBCrDs0GYDyMvJoUxDL0WNGO/0ZwV+965L2//WhDDipwu5LQZTMNpvpaxlwxDMJE9/DDQMscyT0bhH9e9bXUqdlwNxHQhssgMiy4IsTNzxpbScHwnEWtt1B2r9m8elITS6hmFqA86MQAqpGJBwwm/BOHZiuij0Q0peHXnYhIz5aAxE3tt78vDHyXEVfIezBH92MjyrL0NMh7IfY=
  - secure: I7QDw3vUD1TqRokJXWj1xKOP77Zr4ZM6p1i/vPZUMZr6IwSAhDROhBOtCwzR6KHd+H/043AyZ/pSy/tM9jkYXPsyfZhFA6Qq5NdfsNfREBylBOYK+O3ydUYLK/2Z6c2LdllLpD0sxyGW/Aby2JMffwnWRKfNIBVZSmHFmZ4AfMHN60++R1xYVAGocOAyPYpIVCmfH38MpJh+IfQKrwgKnopb2Vb+MCRMgKyHU0QkCmtEC78hPpqwdrucN9hGr3G3OUUL1XP6BOCQYxDesh8cI5PbJnn0NcO4yp3FiaVBk0xbaZksu0VZ7tvk+DpUq1bFsofdxBMb6jBbfUFdLfYa7cYfn8YTmvYPiEbM1Zq9GI0m901JC2c3c8Ic0RbcDiUGHG6RWSrCFg0E/LUp8u/X4KEcv1syYY1PuykRWt7E3C6L5z2dMyu8FTGzT3fGp5AoEG9BARniJSxYR5kWOhTJq7hBwXpZqQQSN7Na7k24MbU43SvhC0Rrcq8VHTz/LPFpkPM5jASQ3O4dhRCKXn5B21VVRVryoCqrSr74/t6zgv0zThvT7I6ilOcpX7m0B30sfD7xml4agbp0GrRY2pPMFoXnefx9pseCi3vH48Ll19tiBPFUr2eaPzHII8y2olMbiey65Vadp3Lv4W644niu2VEZvQDoYov7dIkQYOiI8L4=
  - secure: Fu9B3C0h49w2xucQ9gnDAKE0V7I69SmEbxs+n2o6Eq1Y4LlRmXuW9lYcV8TPR7jRSguMYctjQblUu75B+WZlrPBiqVc+vomNfkHiJEN/bTjincl0xoonCXJSmbY0P1GCJzCdGzL/e25M8LhgsbgaQjWt+hQ2EM2UmRhHiFf5KX2DBlGxwo+uVTzmwIZ4TxLZIcNnCaGrbvGdfd453uKpfgETmjYHNXJwSPYRHxujJU+kfdBXyL6n4qme6nZAzlRb/e/w3GsJZsogI8qq+SupbGF0eUA2PTApHDgJoSrwhXSzleZt4GX45C/w2SD57TEEXudzXjt5OrNNMLdrR508W4PkGXTJ2zhkaCoYuFO6u7qDmvYRt8eLk4PuRVJ8s70UrSvjs2G+pRPGmGxNibUCPv8+fDzHtn2dSjD0jVT92mMAS0jrMxTqwJ1eRWdG5s0fElA91LAoYraAQG5PjXK3bBsxQe2/p5w3AxC4BeaMaFFguJ/Hvqqf65R10nXH2V0X0UQRCncu1aFhkH2BOGlHisTgx5Y1nGGkfdDiCLSQeueqEGMvNEy0+KHesubrffLtG7Yb3dC27DCM1hBuB8E8s7J9jAq3n68NymhGlacDeDSlwTu47LI9ZuS2LRc9SRwcIPM844IGy0JnM3fVwyIxd/TpHL0+hb8yvaR+YH8HneI=
  - secure: p931NXfGOmAKHTp0c+azmfEqcn8FW+z7FlgX+NTxwgm3F/z3n5ePHOqeFu5e4jqQW2vpfCA7N39tjF/SpexUx+moVgsUNq/mW36OGHDk1xCRUHQmBwrZgypybW9gloVHUifpeGqnt1CaHG5OFKwGKCsmaT7xsmo3APcCzc2pS35kV+0D6G5ImQjkbjzLhnDt536sPpCXQU+bhx59FYw9YMdisDIKWzLP0YOMQD0IfPvyru8ucrp7mdNKe2cYPJ+qe665VZCdXC6qXt9flwlsKpzXa9/WGFJp+3FodR2L90PNEZ5v6EG4trxitNput75kSt/JiNa/LuUfDeXfq89CU0wvPYNfmTQdWPv1ekUj1LLHh3uBOH6X54Cgf5B34odIm0yM36bpN0FeZoCj1w79gRINh8YTw7uVJn7o09pc0w9+8aNafDstQZvRztZCB04U1BLMfjnE2lK7CirKq8SKRoYmLr9BOqZ/HF+teV+fjfmPOKUJEEIspJ9ycUNYaPz9JwDTQ58wx6YhTyOVPfFt14lM95NI2Ypfd6pf3A21snLkjWBeg+X5iHa44hONmABZgt64fDKNaYYDx3IDGxotc13jJ7Ez5TqJErc88n6YEyiLkSc9JzVs5rt4TEdXZ8V08C6l8lBd5Prf2bh1hbZJoX5dfWaqORwS4XpIS0OxU74=
